name: phone_numbers_parser
description: Dart library for parsing phone numbers. Inspired by Google's libphonenumber and PhoneNumberKit for ios.
version: 1.0.0
homepage: https://github.com/cedvdb/phone_number_parser
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  phone_number_metadata:
    git: https://github.com/cedvdb/dart_phone_metadata.git


dev_dependencies:
  pedantic: ^1.9.0
  xml: ^5.0.2
  test: any
  path: ^1.8.0


